# Generated by Django 5.1.3 on 2024-12-12 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_app', '0005_alter_quest_description_alter_quest_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='duration',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='quest',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quest',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
