# Generated by Django 5.1.3 on 2024-12-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_app', '0006_quest_completed_at_quest_duration_quest_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='total_points',
            new_name='points',
        ),
    ]
