# Generated by Django 5.1.3 on 2024-12-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_app', '0009_quest_completed_at_alter_quest_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='cost',
            new_name='points_required',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='points',
        ),
    ]
