# Generated by Django 5.1.3 on 2024-12-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_app', '0010_rename_cost_reward_points_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other_field',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
