# Generated by Django 5.1.3 on 2024-12-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_app', '0014_remove_reward_user_alter_reward_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rewards',
            field=models.ManyToManyField(blank=True, to='quest_app.reward'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
