# Generated by Django 5.1.3 on 2024-12-05 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shukanka_quest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='name',
        ),
    ]
